TYPE=VIEW
query=select `orders_details`.`order_id` AS `order_id`,`orders_details`.`user_id` AS `user_id`,`orders_details`.`full_name` AS `full_name`,`orders_details`.`email` AS `email`,`orders_details`.`phone` AS `phone`,`orders_details`.`address` AS `address`,sum(`orders_details`.`total_price`) AS `total_price`,`orders_details`.`transaction_date` AS `transaction_date` from `java_workshop_db`.`orders_details` group by `orders_details`.`order_id`
md5=841cd2f6c1e6d008801cd216f1f1f7b2
updatable=0
algorithm=0
definer_user=admin
definer_host=localhost
suid=2
with_check_option=0
timestamp=2021-09-03 13:09:16
create-version=1
source=SELECT \norder_id, \nuser_id,\nfull_name,\nemail,\nphone,\naddress,\nSUM(total_price) AS total_price,\ntransaction_date\nFROM orders_details \nGROUP BY order_id
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `orders_details`.`order_id` AS `order_id`,`orders_details`.`user_id` AS `user_id`,`orders_details`.`full_name` AS `full_name`,`orders_details`.`email` AS `email`,`orders_details`.`phone` AS `phone`,`orders_details`.`address` AS `address`,sum(`orders_details`.`total_price`) AS `total_price`,`orders_details`.`transaction_date` AS `transaction_date` from `java_workshop_db`.`orders_details` group by `orders_details`.`order_id`
