TYPE=VIEW
query=select `java_workshop_db`.`customers`.`id` AS `id`,`java_workshop_db`.`customers`.`email` AS `email`,`java_workshop_db`.`customers`.`pass` AS `pass`,`java_workshop_db`.`customers`.`first_name` AS `first_name`,`java_workshop_db`.`customers`.`last_name` AS `last_name`,`java_workshop_db`.`customers`.`phone` AS `phone`,`java_workshop_db`.`customers`.`address` AS `address`,`java_workshop_db`.`customers`.`created` AS `created`,`java_workshop_db`.`customers`.`modified` AS `modified`,0 AS `is_admin` from `java_workshop_db`.`customers` union select `java_workshop_db`.`admins`.`id` AS `id`,`java_workshop_db`.`admins`.`email` AS `email`,`java_workshop_db`.`admins`.`pass` AS `pass`,`java_workshop_db`.`admins`.`first_name` AS `first_name`,`java_workshop_db`.`admins`.`last_name` AS `last_name`,`java_workshop_db`.`admins`.`phone` AS `phone`,`java_workshop_db`.`admins`.`address` AS `address`,`java_workshop_db`.`admins`.`created` AS `created`,`java_workshop_db`.`admins`.`modified` AS `modified`,1 AS `is_admin` from `java_workshop_db`.`admins`
md5=24c3816a6f197e95f66bef6b2acc80ab
updatable=0
algorithm=0
definer_user=admin
definer_host=localhost
suid=2
with_check_option=0
timestamp=2021-08-08 13:19:57
create-version=1
source=SELECT *, 0 AS is_admin FROM customers\nUNION\nSELECT *, 1 AS is_admin FROM admins
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `java_workshop_db`.`customers`.`id` AS `id`,`java_workshop_db`.`customers`.`email` AS `email`,`java_workshop_db`.`customers`.`pass` AS `pass`,`java_workshop_db`.`customers`.`first_name` AS `first_name`,`java_workshop_db`.`customers`.`last_name` AS `last_name`,`java_workshop_db`.`customers`.`phone` AS `phone`,`java_workshop_db`.`customers`.`address` AS `address`,`java_workshop_db`.`customers`.`created` AS `created`,`java_workshop_db`.`customers`.`modified` AS `modified`,0 AS `is_admin` from `java_workshop_db`.`customers` union select `java_workshop_db`.`admins`.`id` AS `id`,`java_workshop_db`.`admins`.`email` AS `email`,`java_workshop_db`.`admins`.`pass` AS `pass`,`java_workshop_db`.`admins`.`first_name` AS `first_name`,`java_workshop_db`.`admins`.`last_name` AS `last_name`,`java_workshop_db`.`admins`.`phone` AS `phone`,`java_workshop_db`.`admins`.`address` AS `address`,`java_workshop_db`.`admins`.`created` AS `created`,`java_workshop_db`.`admins`.`modified` AS `modified`,1 AS `is_admin` from `java_workshop_db`.`admins`
